=== RDAJose/EXAMEN-WEB/cine.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="cine">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="pelicula" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="titulo" type="xs:string"/>
                            <xs:element name="director" type="xs:string"/>
                            <xs:element name="anio" type="xs:integer"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== RDAJose/EXAMEN-WEB/cine.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="cine.xsl"?>
<cine
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="cine.xsd">
    <pelicula>
        <titulo>Match Point</titulo>
        <director>Woody Allen</director>
        <anio>2014</anio>
    </pelicula>
    <pelicula>
        <titulo>Death Proof</titulo>
        <director>Quentin Tarantino</director>
        <anio>2007</anio>
    </pelicula>
</cine>
